module.exports = {
    'us-east-2': {region: 'us-east-2', name: 'US East (Ohio)'},
    'us-east-1': {region: 'us-east-1', name: 'US East (N. Virginia)'},
    'us-west-1': {region: 'us-west-1', name: 'US West (N. California)'},
    'us-west-2': {region: 'us-west-2', name: 'US West (Oregon)'},
    'af-south-1': {region: 'af-south-1', name: 'Africa (Cape Town)'},
    'ap-east-1': {region: 'ap-east-1', name: 'Asia Pacific (Hong Kong)'},
    'ap-south-1': {region: 'ap-south-1', name: 'Asia Pacific (Mumbai)'},
    'ap-northeast-3': {region: 'ap-northeast-3', name: 'Asia Pacific (Osaka-Local)'},
    'ap-northeast-2': {region: 'ap-northeast-2', name: 'Asia Pacific (Seoul)'},
    'ap-southeast-1': {region: 'ap-southeast-1', name: 'Asia Pacific (Singapore)'},
    'ap-southeast-2': {region: 'ap-southeast-2', name: 'Asia Pacific (Sydney)'},
    'ap-northeast-1': {region: 'ap-northeast-1', name: 'Asia Pacific (Tokyo)'},
    'ca-central-1': {region: 'ca-central-1', name: 'Canada (Central)'},
    'cn-north-1': {region: 'cn-north-1', name: 'China (Beijing)'},
    'cn-northwest-1': {region: 'cn-northwest-1', name: 'China (Ningxia)'},
    'eu-central-1': {region: 'eu-central-1', name: 'Europe (Frankfurt)'},
    'eu-west-1': {region: 'eu-west-1', name: 'Europe (Ireland)'},
    'eu-west-2': {region: 'eu-west-2', name: 'Europe (London)'},
    'eu-south-1': {region: 'eu-south-1', name: 'Europe (Milan)'},
    'eu-west-3': {region: 'eu-west-3', name: 'Europe (Paris)'},
    'eu-north-1': {region: 'eu-north-1', name: 'Europe (Stockholm)'},
    'me-south-1': {region: 'me-south-1', name: 'Middle East (Bahrain)'},
    'sa-east-1': {region: 'sa-east-1', name: 'South America (São Paulo)'}
};